name: Run Tests on Project

on:
  push:
    branches: [main]
    paths:
      - "microservices/ai-service/**"

  pull_request:
    branches: [main]
    paths:
      - "microservices/ai-service/**"
    
jobs:
    test:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: microservices/ai-service

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Install UV
              uses: astral-sh/setup-uv@v6

            - name: Setup Python
              run: uv python install 3.12

            - name: Install dependencies
              run: uv sync --locked

            - name: Run tests
              run: uv run pytest

